### ISSUE TITLE
Throwing errors display 'Green' notification

### ISSUE THREAD

**Issue by georgebotley** [lekoala/silverstripe-cms-actions#1]
Using `throw new Exception("Show this error");` displays an error message notification but it sends a success notification with the green border and not the red border which would indicate an error.

**Comment by georgebotley** [comment]
Where are you currently defining the error to be shown?

**Comment by georgebotley** [comment]
The CMS uses `ValidationException` i believe

**Comment by lekoala** [comment]
Fixed in https://github.com/lekoala/silverstripe-cms-actions/commit/e62bb2f039fab5a107f8dcf579749452d34fbbbe
