### ISSUE TITLE
Error on button click in SiteConfigExtension

### ISSUE THREAD

**Issue by patjnr** [lekoala/silverstripe-cms-actions#12]
Clicking the CutomeAction button does not seem to be working in SiteConfig Extension.
Getting this error
> [Emergency] Uncaught Exception: Submitted data does not contain an ID and a ClassName

In SiteConfigExtension I have these code snippets.

```
    public function updateCMSActions(FieldList $actions)
    {
       $actions->push(new CustomAction('doSaveCredentials', 'Save API credentials'));
    }
```

Handler

```
 public function doSaveCredentials($data, $form)
    {
        //// THIS IS NOT BEING CALLED
    }
```

**Comment by lekoala** [comment]
I haven't tried yet with the SiteConfig to be honest. Probably that section is not sending the id/class like all other parts of the cms. However, it should be fairly simple to check if the current controller is the one for SiteConfig and fetch the current site config accordingly. Do you want to try to give it a go?

**Comment by patjnr** [comment]
What I figured out is that when editing a SiteConfig instance the form does not have a ClassName field. 

In class ActionsGridFieldItemRequest on line 410

```
} elseif ($controller instanceof LeftAndMain) {
```
When dealing with SiteConfig, this will be true because SiteConfigLeftAndMain extends LeftAndMain. The next statement checks for a ClassName and this is where it dies because $data does not have a key ClassName

```
if (empty($data['ClassName']) || empty($data['ID'])) {
    throw new Exception("Submitted data does not contain and ID and a ClassName");
}
```

To make it work on SiteConfig either do the following

After line 410 add this 'hack'

```
if ($controller instanceof SiteConfigLeftAndMain){
    $data['ClassName'] = SiteConfig::class;
 }
``` 
Or in the DataExtension subclass,  updateCMSFields method, add a HiddenField with ClassName value.

```
$fields->push(HiddenField::create('ClassName')->setValue(SiteConfig::class));
```

**Comment by lekoala** [comment]
i see. i made it a bit simpler in https://github.com/lekoala/silverstripe-cms-actions/releases/tag/1.2.8 it should be fine now

**Comment by patjnr** [comment]
I tested with the new release but the error is still there. I tried to compare the release with the previous one and it looks like there are no changes to that effect, did I miss something?
https://github.com/lekoala/silverstripe-cms-actions/compare/1.2.7...1.2.8

**Comment by lekoala** [comment]
ah yes indeed... i forgot to push ^^ sorry about that
https://github.com/lekoala/silverstripe-cms-actions/releases/tag/1.2.9

**Comment by patjnr** [comment]
Perfect, thank you very much.
