### ISSUE TITLE
Require cms/admin dependencies instead of recipe-cms

### ISSUE THREAD

**Issue by kinglozzer** [lekoala/silverstripe-cms-actions#13]
For projects that don’t use recipe-cms, installing this module will pull in a bunch of dependencies that we don’t necessarily want 😄

**Comment by lekoala** [comment]
good point! actually i think the cms part is not even required

**Comment by lekoala** [comment]
released :-) https://github.com/lekoala/silverstripe-cms-actions/releases/tag/1.2.8
