### ISSUE TITLE
Make "save_prev_next", "save_close" and "delete_right" options opt-in and record-specific

### ISSUE THREAD

**Issue by mleutenegger** [lekoala/silverstripe-cms-actions#15]
Currently, the extra save buttons (and delete button on the right) are enabled by default and enabling/disabling them is global. There are three issues with this approach:

* Using this module as a dependency in another module requires the module to either disable the options by default or communicate config options in order to not have an impact on the entire application where it is installed.
* Adding the buttons globally when only needed for one specific form changes the UI in every edit form, which most likely confuses users.
* There are instances, where "Save & Next" and "Save & Previous" are useful, but especially in huge lists or in instances where the user is sent to the item form from another item, there is no context for the user to realistically understand where he is going to end up after clicking the button.

Please let me know what you think of the idea, I'd be happy to contribute a PR!

**Comment by lekoala** [comment]
I think the delete action on the right needs to stay global but I agree that the save and next/prev does not always make sense. If you find a nice way to deal with this I'm happy to merge a PR that does that :)

**Comment by lekoala** [comment]
@mleutenegger 
https://github.com/lekoala/silverstripe-cms-actions/releases/tag/1.3.5
this should be a good step in the right direction

**Comment by mleutenegger** [comment]
That's actually very good and close to what I was looking for. Thanks!
