### ISSUE TITLE
Extend GridFieldRowButton to be a bit more flexible?

### ISSUE THREAD

**Issue by micschk** [lekoala/silverstripe-cms-actions#16]
PR coming up with changes (some breaking so would need a version bump):
- Allow non-icon (text) buttons (including BS 'btn-dark' etc styles)
- Allow inserting in custom column name
- Allow setting if button should use ajax or not (eg inline refresh)
- Provide `$gridField`, `$record` & `$columnName` to the `getButtonLabel()` method to allow using it as a toggle button

## Use case
Publications which can be toggled between 'Approved' and 'Disapproved' state (button reflects state):
<img width="1386" alt="Screenshot 2022-02-10 at 10 56 25" src="https://user-images.githubusercontent.com/1005986/153382892-7fcff34d-1d42-4ea4-aa3e-40cb63eb53dd.png">

**Comment by lekoala** [comment]
@micschk that looks great! i've merged the pr and i will review it shortly on my project to see if anything breaks. at first sight it doesn't seem there is a lot of breaking changes?

**Comment by micschk** [comment]
Only real 'breaking' change is that [this method](https://github.com/lekoala/silverstripe-cms-actions/blob/b626d78f36ac9553ca40e0e83051db132b2baeee/src/GridFieldRowButton.php#L77):
```
abstract function getButtonLabel()
```

Has been changed to require accepting three arguments:
```
abstract function getButtonLabel(GridField $gridField, $record, $columnName);
```
