### ISSUE TITLE
Create & Close still works when canCreate is false.

### ISSUE THREAD

**Issue by georgebotley** [lekoala/silverstripe-cms-actions#2]
Another little item. 

The Create and Close button displays and carries out its functionality where `canCreate` is disallowed for that DataObject. 

P.S. Great module and I'm having success implementing it so far!

**Comment by lekoala** [comment]
i made a small change in https://github.com/lekoala/silverstripe-cms-actions/commit/d8651e5f250a66bb7f6a0bfe75ee608d5b794f77

but the save itself is delegated to GridFieldDetailForm_ItemRequest::doSave that only checks "canEdit" so probably it's better to fix the framework itself

**Comment by lekoala** [comment]
closing this, feel free to reopen if you think it needs further work
