### ISSUE TITLE
Regression in display logic

### ISSUE THREAD

**Issue by gurucomkz** [lekoala/silverstripe-cms-actions#28]
The change to `src/ActionsGridFieldItemRequest.php` in https://github.com/lekoala/silverstripe-cms-actions/pull/22/files#diff-b7a004efabbd9cbfe65185f34b596f2aa2af6736d611d4a034b76f7b2e4f42b5R107 from @Firesphere  had introduced a breaking change - action buttons stopped being displayed for fresh and readonly items.

There may be any number of reasons to continue displaying the action buttons for the readonly records:
* provide some external links
* some programmatic actions on the object itself
* shorthand actions for the related objects
* ...etc

However, the above mentioned change stopped displaying the buttons altogether.

I'm suggesting to revert the changes related to the introduced checkCan() method.

**Comment by lekoala** [comment]
@gurucomkz so hopefully this is fixed in https://github.com/lekoala/silverstripe-cms-actions/releases/tag/1.3.10
