### ISSUE TITLE
Save, Save & Close etc... not publishing assets or running on before/AfterWrite etc.

### ISSUE THREAD

**Issue by georgebotley** [lekoala/silverstripe-cms-actions#3]
### Issue

I've built a site for a client which used the asset uploader within the Member object for "Blog Author Photo". This functionality is actually provided by the official SilverStripe Blog module. However, when your module is installed as well the staff are unable to add photos in this field because they remain in the 'Draft' state on clicking Save, or any of this modules Save buttons. 

### Replication:

- Install silverstripe-blog and this module 
- Visit your own user profile in SilverStripe add a photo and click Save... that should work as expected. 
- Now try that same action via the Member LeftAndMain GridField you'll notice any image changes remain in draft.

### Other Observations

I initially thought it might've been linked to the the SilverStripe blog not setting ownership on the assets, but it does, as witnessed by the actual user profile saving correctly. I tried to perhaps manually work around this with an onBeforeWrite or an onAfterWrite method call in a DataExtension on the Member object but these don't seem to get invoked in the usual way. 

Can you explain how the flow works for this module calling the save actions? I can't seem to work my head around it looking in the source as I'd have tried to patch it and put a pull request in otherwise.

**Comment by lekoala** [comment]
Hey, I made a fresh install and installed the blog module. Then, I created a model admin for the members using the default settings.

As far as I can tell, using the regular "save" works just fine. "save and close" works too, but somehow if you visit page again, it's not refreshing the status of the uploader (so, it's still shown as being "draft" with a little green checkmark showing it's uploaded... but actually, it is published). You can confirm by clicking on the little eye and see the file is indeed published.

So I think it's just the state of the uploader that is somehow cached by silverstripe in between ajax navigation. If you refresh the page, it is displayed properly. Can you confirm this behavior on your end?

**Comment by georgebotley** [comment]
That's fair, but if you try and load that asset in a template it won't load. In my case anyway

**Comment by lekoala** [comment]
Mhhh.. since the asset is published (even if the uploader doesn't say so) it should be working. it is for me anyway. could you share like a screen recording or some code that I could have a look at ?

**Comment by georgebotley** [comment]
Interesting, I'll check a couple other things over. The browser console is helpful as ever with its reasons.

**Comment by georgebotley** [comment]
Is there any way to disable the module for certain parts of the Admin? I just want to ascertain if it's perhaps any other customisations on this particular installation. Thanks for your help with this once again :-)

**Comment by lekoala** [comment]
well it depends. does it fail if you press on the regular "save" button? this is what i would do 
- if it works with "save" and not with "save and close" => i would look here https://github.com/lekoala/silverstripe-cms-actions/blob/master/src/ActionsGridFieldItemRequest.php#L487
- it neither works it means somehow the extension is messing up publishing the asset. i don't see why, since it should not have any side effect other that updating the editform. but you can always return early in https://github.com/lekoala/silverstripe-cms-actions/blob/master/src/ActionsGridFieldItemRequest.php#L487 with somethin like "if controller::curr() instanceof MyMemberController => return null)

**Comment by lekoala** [comment]
I'm closing the issue feel free to reopen if you have more details
