### ISSUE TITLE
Updating cms-actions to support Silverstripe 5

### ISSUE THREAD

**Issue by cotpat** [lekoala/silverstripe-cms-actions#33]
We are currently preparing to migrate our site to Silverstripe 5 and checking & updating our dependencies.

However, our site is dependant on silverstripe-cms-actions and it has not yet been updated to support SS5.

Is such an update in the pipeline? If so, I would gladly offer my assistance in the process, once a procedure has been defined.

**Comment by lekoala** [comment]
My plan is to migrate most of my websites over the summer so that's probably when I'll have a better look at it :-)

If you have time and energy to make a PR, I'd be more than happy to review it and start branch 1.4

**Comment by cotpat** [comment]
I will certainly look into it. Do you plan on supporting SS4 as well as SS5 in 1.4 or on moving SS4 support into a separate branch?

**Comment by lekoala** [comment]
if we can support both its better. as far as i can tell, it shouldn't not make a big difference from ss4 anyway.

**Comment by lekoala** [comment]
released as 1.4.0, no major issues found so far
