### ISSUE TITLE
Can GridFieldRowButton be paired with PureModal?

### ISSUE THREAD

**Issue by mooror** [lekoala/silverstripe-cms-actions#37]
I have an idea for a duplication action that would allow a user to duplicate a DataObject in a gridfield while updating some of its fields at the same time. So I was thinking of using the PureModal you have designed to do so.

Now I know I can create something like this and place it in the DataObjects interface in the form of a new button using `PureModalAction` (which is not a bad solution at all). But I was hoping to be able to do this from the Gridfield itself, instead of having to click into the DataOject first. Is it possible to create a Gridfield action that would act in a similar way to `PureModalAction`?

**Comment by lekoala** [comment]
i guess that should be possible but it will require a few tweaks

however, given your use case, it's probably much easier to have a row button that redirects to a /new form and fill in the values from the object you want to duplicate, with some get parameter, eg : /new?duplicate_from=ID
this will make the whole ui much easier to reason about (validation, etc)

**Comment by mooror** [comment]
Quite late now, but I realized that I never responded to your answer.

Thank you for taking the time to answer my question @lekoala 🎊
