### ISSUE TITLE
error with SilverStripe\Admin\LeftAndMain::getRecord()

### ISSUE THREAD

**Issue by sunnysideup** [lekoala/silverstripe-cms-actions#38]
Not sure what to make of this or if this is even an error. 

![image](https://github.com/lekoala/silverstripe-cms-actions/assets/167154/e0ec52be-447e-422a-bc67-49413ac33842)

[Emergency] Uncaught ArgumentCountError: Too few arguments to function SilverStripe\Admin\LeftAndMain::getRecord(), 0 passed in /var/www/ss4/mysite/vendor/lekoala/silverstripe-cms-actions/src/ActionsGridFieldItemRequest.php on line 145 and exactly 1 expected

**Comment by lekoala** [comment]
i've merged your PR, does it fix your issue?

**Comment by sunnysideup** [comment]
yes, it worked, but I am not sure if passing zero is the right thing to do.

**Comment by lekoala** [comment]
i will have a deeper look at it. i'll probably add a bit of reflection to make sure it gets an argument or not

**Comment by lekoala** [comment]
i've improved things a little bit here

https://github.com/lekoala/silverstripe-cms-actions/commit/7ea6559d52efbe739481cbdf49c885711b621dd4

should work the same for you, but avoiding passing a parameter when not needed
