### ISSUE TITLE
Button icon alignment is out

### ISSUE THREAD

**Issue by purplespider** [lekoala/silverstripe-cms-actions#4]
Firstly, this module is amazing!

One minor issue I've noticed is that when using `setButtonIcon()`, the icon seems a bit out of alignment compared with other buttons:

<img width="512" alt="Screenshot 2021-08-30 at 15 03 56@2x" src="https://user-images.githubusercontent.com/329880/131352010-27fef85c-0dcc-42bd-8151-e442e908bad1.png">

See how the icons in the blue action buttons display higher than in the save buttons and have less margin between the icon and the button label.

**Comment by lekoala** [comment]
@purplespider  thanks for the positive feedback

it should be fixed in 1.2.1

**Comment by purplespider** [comment]
Thanks for looking at this so quickly! It's definitely an improvement, but I noticed that the CSS addition affected all buttons in the CMS, not just the module's buttons.

I discovered that for Silverstripe buttons, the icon classes are added via `extraClasses` directly to the button, rather than to a span within the button, so I've created a PR to make the module do the same: #5
