### ISSUE TITLE
confirmation message triggers on "cancel" when setNoAjax is true

### ISSUE THREAD

**Issue by wernerkrauss** [lekoala/silverstripe-cms-actions#40]
Hi Lekoala,

thanks for your very useful module.

When I have a custom action with confirmation message, the message is triggerd when I click "cancel" or "ok" on a button that should download something, therefor I added `setNoAjax(true)`:

```
            $exportAction = CustomLink::create('doExport', 'Export Translations');
            $exportAction->setButtonIcon(SilverStripeIcons::ICON_EXPORT);
            $exportAction->setNoAjax(true);
            $exportAction->setConfirmation(_t(self::class . '.EXPORT_CONFIRMATION', 'Export all {locale} translations?', ['locale' => $this->owner->Locale]));
            $actions->push($exportAction);
```

Tested in Firefox and Chrome.

PS: it would be a great pleasure to meet you at next www.stripecon.eu, as your work is very important for the European community!

**Comment by lekoala** [comment]
Hey good catch, never tried that before :-)

easy fix:
https://github.com/lekoala/silverstripe-cms-actions/releases/tag/1.7.4

PS: each year I'm looking at stripecon, but I never manage to decide myself to go to it :-D

**Comment by wernerkrauss** [comment]
Thanks for looking into that. Now it triggers the action on load of the ModelAdmin item.

If you want to test it on a demo with Fluent enabled:

See https://github.com/wernerkrauss/silverstripe-fluent-export-import/

Uncomment line https://github.com/wernerkrauss/silverstripe-fluent-export-import/blob/main/src/Extension/LocaleExportImport.php#L36

**Comment by wernerkrauss** [comment]
well, of course it hits my export action when I reload that link ;) But still it doesn't seem to work properly :(

**Comment by lekoala** [comment]
@wernerkrauss yep, i missed a e.preventDefault() to prevent silverstripe from sending the form

https://github.com/lekoala/silverstripe-cms-actions/releases/tag/1.7.5
