### ISSUE TITLE
Unrelated canEdit negatively affects CMSAction

### ISSUE THREAD

**Issue by dcentrica** [lekoala/silverstripe-cms-actions#41]
Using a simple `CMSAction` the resulting button is rendered as disabled by default. If I fiddle with the relevant object's canXX() return values, it turns out that the button will automatically be rendered as disabled if `canEdit()` returns `false`. This doesn't appear to be intuitive given that these buttons should be able to be used for arbitrary purposes unrelated to "editing" as is the case with my app.

The latest version of the module where I can see it behaves itself OK is `v1.4.1`, the next available release is `v1.5.0` where it stopped working (The button started appearing as being disabled). It also doesn't work in latest stable `v1.7.5` (I can reliably switch between the two and observe the change in behaviour). 

`silverstripe/framework` `v5.2.22`
`lekoala/silverstripe-cms-actions` `1.5.0`

This is how the logic is strung together:

```
    /**
     * Generate a custom link for display of a "Run" action next to the standard "Save" button.
     *
     * @param  string $action One of 'run' or 'notify'.
     * @return CustomLink|CustomAction
     * @see    getCMSActions()
     */
    private function policyRunAction(string $action): CustomLink|CustomAction
    {
        $link = sprintf(
            '%s/EditForm/field/Teams/item/%d/ItemEditForm/field/Policies/item/%d/view#Root_Runs',
            Controller::curr()->Link(),
            $this->getField('TeamID'),
            $this->getField('ID')
        );

        if ($action === 'run') {
            return CustomAction::create('execute', 'Run')
                ->setRedirectURL($link)
                ->setButtonIcon(SilverStripeIcons::ICON_ROCKET);
        }

        if ($action === 'notify') {
            return CustomAction::create('notify', 'Run & Notify')
                ->setRedirectURL($link)
                ->setButtonIcon(SilverStripeIcons::ICON_COMMENT);
        }

        return CustomLink::create('', null);
    }
```

```
/**
 * @return FieldList
 */
public function getCMSActions(): FieldList
{
    $actions = parent::getCMSActions();

    if ($this->exists() && $this->canExecute()) {
        $actions->push($this->policyRunAction('run'));
        $actions->push($this->policyDownloadAction());

        if ($this->canSendNotifications()) {
            $actions->push($this->policyRunAction('notify'));
        }
    }

    return $actions;
}
```

**Comment by lekoala** [comment]
yes it's very likely due to the change from using updateFormActions instead of updateItemEditForm
i might actually need to use both (updateFormActions for the saveXXX actions, and updateItemEditForm for the rest)

**Comment by lekoala** [comment]
so yes i'm pretty sure the issue rises from here

https://github.com/silverstripe/silverstripe-framework/blob/4d78f781bb54596917b1b78dd09e0dd374bfbfc5/src/Forms/GridField/GridFieldDetailForm_ItemRequest.php#L255-L276

the gridfield form checks canEdit and makes the whole form readonly, including actions, if canEdit is false... which doesn't allow customizing canXXX for individual actions

i can probably simply use back the old way of 1.4.x branch , let me give it a try

**Comment by lekoala** [comment]
@dcentrica dev-master should fix your issue. can you confirm? if so i will happily release a new version

**Comment by dcentrica** [comment]
> @dcentrica dev-master should fix your issue. can you confirm? if so i will happily release a new version

Yes! Fixed, thanks so much :-)

**Comment by dcentrica** [comment]
Any chance of a release-tag please? Thank you :-)

**Comment by lekoala** [comment]
and done!
https://github.com/lekoala/silverstripe-cms-actions/releases/tag/1.7.6
